### ISSUE TITLE
low-quality samples

### ISSUE THREAD

**Issue by yulijia** [SydneyBioX/CellSPA#5]
Hi,
I am working with some low-quality samples, where each cell detects only about 10 genes with expression values. When I run the `processingSPE` function, it automatically calculates the UMAP using `scater::runUMAP`. However, I cannot adjust the parameters inside the `runUMAP` function, which causes an error message for my low-quality samples.

>Warning in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  :
  You're computing too large a percentage of total singular values, use a standard svd instead.
11:30:15 UMAP embedding parameters a = 0.9922 b = 1.112
11:30:15 Read 3 rows and found 2 numeric columns
Error in uwot(X = X, n_neighbors = n_neighbors, n_components = n_components,  : 
  n_neighbors must be smaller than the dataset size
In addition: Warning message:
In check_numbers(k = k, nu = nu, nv = nv, limit = min(dim(x)) -  :
  more singular values/vectors requested than available
  
Do you think we could modify the function to pass more parameters to the internal functions? Or should we establish a standard to determine if the input data is of low quality when running the processingSPE function and then return a message that we don't handle such low-quality samples?

**Comment by YingxinLin** [comment]
Thank you for the suggestions. I have incorporated this in the latest commit.
